// export const homeObjOne = {
//   id: "about",
//   lightBg: false,
//   lightText: true,
//   lightTextDesc: true,
//   topLine: "About",
//   headLine: "I am interested in a career as a Full Stack Developer ",
//   description: "I am interested in a career as a Full Stack Developer ",
//   buttonLabel: "FrontEnd",
//   imgStart: false,
//   img: require("../../images/imgg.png"),
//   alt: "img6",
//   dark: true,
//   primary: true,
//   darkText: false,
// };

// export const homeObjTwo = {
//   id: "projects",
//   lightBg: true,
//   lightText: false,
//   lightTextDesc: false,
//   topLine: "Project",
//   headLine: "Projects",
//   description: "These are my projects",
//   buttonLabel: "Github",

//   imgStart: true,
//   img: require("../../images/per.svg"),
//   alt: "img6",
//   dark: false,
//   primary: false,
//   darkText: true,
// };
export const homeObjTwo = {
  id: "about",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  // topLine: "About ",
  headLine: "About",
  //   description: " ",
  buttonLabel: "Github",
  imgStart: false,

  // img: require("../../images/per.svg"),
  //alt: "img6",
  dark: false,
  primary: false,
  darkText: true,
};
